### PR TITLE
fix package.json as utf 8

### PR DESCRIPTION
**Pull request by grantgeorge**
fix encoding of file (this breaks yarn installations and CI builds)

- Change encoding of package.json from utf-8 [with DOM] to utf-8

### CODE REVIEW

**Comment by jnfeinstein** [comment]
@timelf123 are you maintaining this project?  Would be great to merge this so I can point to official repo instead of a fork.  Much gratitude.

**Comment by roopakv** [comment]
Would LOVE if this could be merged in! this is kind of blocking us on a few fronts :(

**Comment by timelf123** [comment]
Sorry for the delay

**Comment by roopakv** [comment]
Sweet, do you know if npm has to be force refreshed updated or do they pick this up automatically?

might be easier to just bump up the version to 0.1.4 :)

**Comment by roopakv** [comment]
Could you update both yarn and npm please :)

**Comment by timelf123** [comment]
Yes will cut a release later this week, in the process of migrating to a new workspace now - in the mean time feel free to use the #master branch like so:

`angulartics-mixpanel: 'https://github.com/angulartics/angulartics-mixpanel.git#master'`

**Comment by roopakv** [comment]
Trying to avoid using #master :P will wait for you to cut the release! Thank you so much

**Comment by timelf123** [comment]
0.1.4 out now

**Pull request merged**
